"""
generate_nb08_consolidation.py
Generates: SoilHive/notebook/08_data_consolidation.ipynb

Uses vectorized rasterio reads for fast SoilGrids extraction.
"""
import nbformat as nbf
import os

NB_PATH = "/home/agbelgaid/Documents/WORKSPACE/DataCollection/SoilHive/notebook/08_data_consolidation.ipynb"
os.makedirs(os.path.dirname(NB_PATH), exist_ok=True)

nb = nbf.v4.new_notebook()
nb.metadata["kernelspec"] = {
    "display_name": "agent",
    "language": "python",
    "name": "agent",
}
nb.metadata["language_info"] = {
    "name": "python",
    "version": "3.11.0",
}

cells = []

# ── Cell 0 — Title markdown ──────────────────────────────────────────────────
cells.append(nbf.v4.new_markdown_cell(
    "# NB08 — SoilHive Data Consolidation\n"
    "Consolidate WoSIS point data and SoilGrids raster extractions across all countries\n"
    "into a single station-level merged dataset."
))

# ── Cell 1 — Imports & constants ─────────────────────────────────────────────
cells.append(nbf.v4.new_code_cell(
    "import os, glob, warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import rasterio\n"
    "from rasterio.transform import rowcol\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "DATA_DIR = \"/home/agbelgaid/Documents/WORKSPACE/DataCollection/SoilHive/data\"\n"
    "OUTPUT_DIR = \"/home/agbelgaid/Documents/WORKSPACE/DataCollection/SoilHive/reports\"\n"
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n"
    "\n"
    "# SoilGrids depth layers for 0-30cm weighted average\n"
    "# weights: 0-5cm=5, 5-15cm=10, 15-30cm=15 -> total 30\n"
    "SG_DEPTHS = [\"0-5cm\", \"5-15cm\", \"15-30cm\"]\n"
    "SG_WEIGHTS = [5, 10, 15]\n"
    "\n"
    "# SoilGrids divisors (to convert to standard units)\n"
    "SG_DIVISORS = {\n"
    "    \"bdod\": 100,   # cg/cm3 -> g/cm3\n"
    "    \"cec\": 10,     # mmol/kg -> cmolc/kg\n"
    "    \"cfvo\": 10,    # cm3/dm3 -> %\n"
    "    \"clay\": 10,    # g/kg -> %\n"
    "    \"nitrogen\": 100, # cg/kg -> g/kg (approx N%)\n"
    "    \"ocd\": 10,\n"
    "    \"phh2o\": 10,   # pH*10 -> pH\n"
    "    \"sand\": 10,\n"
    "    \"silt\": 10,\n"
    "    \"soc\": 10,\n"
    "    \"wv0010\": 10,\n"
    "    \"wv0033\": 10,\n"
    "    \"wv1500\": 10,\n"
    "}\n"
    "\n"
    "print(\"Imports OK\")\n"
    "print(f\"DATA_DIR: {DATA_DIR}\")\n"
    "print(f\"OUTPUT_DIR: {OUTPUT_DIR}\")"
))

# ── Cell 2 — Helper functions (vectorized) ────────────────────────────────────
cells.append(nbf.v4.new_code_cell(
    "def get_country_folders(data_dir):\n"
    "    return sorted([\n"
    "        d for d in os.listdir(data_dir)\n"
    "        if os.path.isdir(os.path.join(data_dir, d))\n"
    "        and not d.startswith((\"Y\", \"Z\"))\n"
    "    ])\n"
    "\n"
    "\n"
    "def load_wosis(country_folder):\n"
    "    \"\"\"Load output_data_points.csv for a country.\"\"\"\n"
    "    path = os.path.join(country_folder, \"output_data_points.csv\")\n"
    "    if not os.path.exists(path):\n"
    "        return None\n"
    "    df = pd.read_csv(path)\n"
    "    df[\"country\"] = os.path.basename(country_folder)\n"
    "    return df\n"
    "\n"
    "\n"
    "def extract_sg_vectorized(tif_path, lats, lons):\n"
    "    \"\"\"\n"
    "    Vectorized extraction: read the entire raster array once,\n"
    "    then index all (lat, lon) pairs at once.\n"
    "    Returns numpy array of float values (NaN where out-of-bounds or NoData).\n"
    "    \"\"\"\n"
    "    try:\n"
    "        with rasterio.open(tif_path) as src:\n"
    "            arr = src.read(1).astype(float)\n"
    "            nodata = src.nodata\n"
    "            transform = src.transform\n"
    "            h, w = src.height, src.width\n"
    "\n"
    "        rows_arr, cols_arr = rowcol(transform, lons, lats)\n"
    "        rows_arr = np.asarray(rows_arr, dtype=int)\n"
    "        cols_arr = np.asarray(cols_arr, dtype=int)\n"
    "\n"
    "        valid = (rows_arr >= 0) & (rows_arr < h) & (cols_arr >= 0) & (cols_arr < w)\n"
    "        vals = np.full(len(lats), np.nan)\n"
    "        vals[valid] = arr[rows_arr[valid], cols_arr[valid]]\n"
    "        if nodata is not None:\n"
    "            vals[vals == nodata] = np.nan\n"
    "        return vals\n"
    "    except Exception:\n"
    "        return np.full(len(lats), np.nan)\n"
    "\n"
    "\n"
    "def get_sg_0_30cm_average_batch(sg_folder, sg_prop, lats, lons):\n"
    "    \"\"\"\n"
    "    Compute weighted average of SoilGrids property over 0-30cm\n"
    "    for all stations at once (vectorized).\n"
    "    Returns numpy array of float values.\n"
    "    \"\"\"\n"
    "    accum = np.zeros(len(lats))\n"
    "    weight_accum = np.zeros(len(lats))\n"
    "\n"
    "    for depth, w in zip(SG_DEPTHS, SG_WEIGHTS):\n"
    "        tif = os.path.join(sg_folder, f\"{sg_prop}_{depth}_mean.tif\")\n"
    "        if not os.path.exists(tif):\n"
    "            continue\n"
    "        vals = extract_sg_vectorized(tif, lats, lons)\n"
    "        good = ~np.isnan(vals)\n"
    "        accum[good] += vals[good] * w\n"
    "        weight_accum[good] += w\n"
    "\n"
    "    result = np.full(len(lats), np.nan)\n"
    "    has_data = weight_accum > 0\n"
    "    divisor = SG_DIVISORS.get(sg_prop, 1)\n"
    "    result[has_data] = np.round(accum[has_data] / weight_accum[has_data] / divisor, 4)\n"
    "    return result\n"
    "\n"
    "\n"
    "def get_available_sg_properties(sg_folder):\n"
    "    \"\"\"List unique SoilGrids property names available in the folder.\"\"\"\n"
    "    tifs = glob.glob(os.path.join(sg_folder, \"*.tif\"))\n"
    "    props = sorted(set(os.path.basename(t).split(\"_\")[0] for t in tifs))\n"
    "    return props\n"
    "\n"
    "\n"
    "print(\"Helper functions defined (vectorized mode).\")"
))

# ── Cell 3 — Phase 1: Inventory ───────────────────────────────────────────────
cells.append(nbf.v4.new_markdown_cell("## Phase 1 — Inventory all countries"))

cells.append(nbf.v4.new_code_cell(
    "print(\"=\" * 80)\n"
    "print(\"PHASE 1 - INVENTORY\")\n"
    "print(\"=\" * 80)\n"
    "\n"
    "countries = get_country_folders(DATA_DIR)\n"
    "inventory = []\n"
    "\n"
    "for c in countries:\n"
    "    base = os.path.join(DATA_DIR, c)\n"
    "    sg_folder = os.path.join(base, \"SoilGrids_250m\")\n"
    "\n"
    "    df = load_wosis(base)\n"
    "    n_rows = len(df) if df is not None else 0\n"
    "    n_stations = df.groupby([\"lat\",\"lon\"]).ngroups if df is not None else 0\n"
    "    n_wosis_props = df[\"property\"].nunique() if df is not None else 0\n"
    "    wosis_props = sorted(df[\"property\"].unique().tolist()) if df is not None else []\n"
    "\n"
    "    has_sg = os.path.isdir(sg_folder)\n"
    "    tifs = glob.glob(os.path.join(sg_folder, \"*.tif\")) if has_sg else []\n"
    "    sg_props = get_available_sg_properties(sg_folder) if has_sg else []\n"
    "\n"
    "    inventory.append({\n"
    "        \"country\": c,\n"
    "        \"n_rows\": n_rows,\n"
    "        \"n_stations\": n_stations,\n"
    "        \"n_wosis_props\": n_wosis_props,\n"
    "        \"wosis_props\": wosis_props,\n"
    "        \"has_sg\": has_sg,\n"
    "        \"n_sg_tifs\": len(tifs),\n"
    "        \"n_sg_props\": len(sg_props),\n"
    "        \"sg_props\": sg_props,\n"
    "    })\n"
    "    print(f\"  {c:45s} | {n_stations:5d} stations | {n_wosis_props:2d} WoSIS props | {len(sg_props):2d} SG props\")\n"
    "\n"
    "inv_df = pd.DataFrame(inventory)\n"
    "print(f\"\\nTOTAL: {len(countries)} countries, {inv_df['n_stations'].sum():,} stations, {inv_df['n_rows'].sum():,} rows\")\n"
    "print(f\"With SoilGrids: {inv_df['has_sg'].sum()} countries\")"
))

# ── Cell 4 — Phase 2: Load and combine all WoSIS ──────────────────────────────
cells.append(nbf.v4.new_markdown_cell("## Phase 2 — Consolidate WoSIS Data"))

cells.append(nbf.v4.new_code_cell(
    "print(\"=\" * 80)\n"
    "print(\"PHASE 2 - CONSOLIDATE WoSIS DATA\")\n"
    "print(\"=\" * 80)\n"
    "\n"
    "all_wosis = []\n"
    "issues = []\n"
    "\n"
    "for c in countries:\n"
    "    base = os.path.join(DATA_DIR, c)\n"
    "    df = load_wosis(base)\n"
    "    if df is None:\n"
    "        issues.append({\"country\": c, \"issue\": \"missing output_data_points.csv\"})\n"
    "        continue\n"
    "\n"
    "    # Check for stations with no data (all values NaN)\n"
    "    station_completeness = df.groupby([\"lat\",\"lon\"])[\"value\"].apply(lambda x: x.notna().sum())\n"
    "    empty_stations = (station_completeness == 0).sum()\n"
    "    if empty_stations > 0:\n"
    "        issues.append({\"country\": c, \"issue\": f\"{empty_stations} stations with 0 non-null values\"})\n"
    "\n"
    "    all_wosis.append(df)\n"
    "\n"
    "wosis_df = pd.concat(all_wosis, ignore_index=True)\n"
    "print(f\"Combined WoSIS dataset: {len(wosis_df):,} rows\")\n"
    "print(f\"Countries: {wosis_df['country'].nunique()}\")\n"
    "print(f\"Total unique stations: {wosis_df.groupby(['lat','lon','country']).ngroups:,}\")\n"
    "print(f\"Properties: {sorted(wosis_df['property'].unique().tolist())}\")\n"
    "print(f\"\\nIssues found: {len(issues)}\")\n"
    "for iss in issues:\n"
    "    print(f\"  {iss['country']}: {iss['issue']}\")"
))

# ── Cell 5 — Phase 3: SoilGrids extraction (vectorized) ───────────────────────
cells.append(nbf.v4.new_markdown_cell("## Phase 3 — Extract SoilGrids Values at Station Locations"))

cells.append(nbf.v4.new_code_cell(
    "print(\"=\" * 80)\n"
    "print(\"PHASE 3 - EXTRACT SOILGRIDS VALUES AT STATION LOCATIONS (vectorized)\")\n"
    "print(\"=\" * 80)\n"
    "\n"
    "sg_frames = []\n"
    "sg_errors = []\n"
    "n_processed = 0\n"
    "\n"
    "for item in inventory:\n"
    "    c = item[\"country\"]\n"
    "    if not item[\"has_sg\"] or not item[\"sg_props\"]:\n"
    "        sg_errors.append({\"country\": c, \"issue\": \"no SoilGrids data\"})\n"
    "        continue\n"
    "\n"
    "    base = os.path.join(DATA_DIR, c)\n"
    "    sg_folder = os.path.join(base, \"SoilGrids_250m\")\n"
    "    df = load_wosis(base)\n"
    "    if df is None:\n"
    "        continue\n"
    "\n"
    "    # Unique stations as numpy arrays for vectorized extraction\n"
    "    stations = df[[\"lat\",\"lon\"]].drop_duplicates().reset_index(drop=True)\n"
    "    lats = stations[\"lat\"].values\n"
    "    lons = stations[\"lon\"].values\n"
    "    sg_props = item[\"sg_props\"]\n"
    "\n"
    "    print(f\"  {c}: {len(stations)} stations x {len(sg_props)} SG props...\", end=\" \", flush=True)\n"
    "\n"
    "    rec = {\"country\": c, \"lat\": lats, \"lon\": lons}\n"
    "    for prop in sg_props:\n"
    "        rec[f\"sg_{prop}\"] = get_sg_0_30cm_average_batch(sg_folder, prop, lats, lons)\n"
    "\n"
    "    frame = pd.DataFrame(rec)\n"
    "    count_ok = frame[[col for col in frame.columns if col.startswith(\"sg_\")]].notna().any(axis=1).sum()\n"
    "    print(f\"{count_ok}/{len(stations)} stations with >=1 SG value\")\n"
    "\n"
    "    sg_frames.append(frame)\n"
    "    n_processed += 1\n"
    "\n"
    "sg_df = pd.concat(sg_frames, ignore_index=True) if sg_frames else pd.DataFrame()\n"
    "sg_cols = [col for col in sg_df.columns if col.startswith(\"sg_\")] if len(sg_df) > 0 else []\n"
    "\n"
    "print(f\"\\nSoilGrids extraction complete:\")\n"
    "print(f\"  {len(sg_df):,} station records\")\n"
    "print(f\"  {len(sg_cols)} SG property columns\")\n"
    "if sg_cols:\n"
    "    print(f\"\\nCoverage per SG property:\")\n"
    "    for col in sg_cols:\n"
    "        n = sg_df[col].notna().sum()\n"
    "        pct = n / len(sg_df) * 100\n"
    "        print(f\"  {col:25s}: {n:5d}/{len(sg_df)} ({pct:.1f}%)\")"
))

# ── Cell 6 — Phase 4: Merge WoSIS + SoilGrids ────────────────────────────────
cells.append(nbf.v4.new_markdown_cell("## Phase 4 — Merge WoSIS + SoilGrids"))

cells.append(nbf.v4.new_code_cell(
    "print(\"=\" * 80)\n"
    "print(\"PHASE 4 - MERGE WoSIS + SOILGRIDS\")\n"
    "print(\"=\" * 80)\n"
    "\n"
    "# Pivot WoSIS: aggregate by (country, lat, lon, property) -> mean of 0-30cm\n"
    "wosis_0_30 = wosis_df[\n"
    "    (wosis_df[\"upper_depth_cm\"] < 30) | (wosis_df[\"lower_depth_cm\"] <= 30)\n"
    "].copy()\n"
    "\n"
    "wosis_wide = (\n"
    "    wosis_0_30\n"
    "    .groupby([\"country\", \"lat\", \"lon\", \"property\"])[\"value\"]\n"
    "    .mean()\n"
    "    .unstack(\"property\")\n"
    "    .reset_index()\n"
    ")\n"
    "wosis_wide.columns.name = None\n"
    "\n"
    "print(f\"WoSIS wide (0-30cm): {wosis_wide.shape}\")\n"
    "print(f\"Columns: {wosis_wide.columns.tolist()[:15]}...\")\n"
    "\n"
    "# Merge with SoilGrids\n"
    "if len(sg_df) > 0:\n"
    "    merged = wosis_wide.merge(sg_df, on=[\"country\",\"lat\",\"lon\"], how=\"left\")\n"
    "else:\n"
    "    merged = wosis_wide.copy()\n"
    "print(f\"\\nMerged dataset: {merged.shape}\")\n"
    "\n"
    "# Missing values report\n"
    "prop_cols = [col for col in wosis_wide.columns if col not in [\"country\",\"lat\",\"lon\"]]\n"
    "print(f\"\\nWoSIS property coverage (0-30cm stations):\")\n"
    "for col in prop_cols:\n"
    "    if col in merged.columns:\n"
    "        n = merged[col].notna().sum()\n"
    "        pct = n / len(merged) * 100\n"
    "        print(f\"  {col:15s}: {n:5d}/{len(merged)} ({pct:.1f}%)\")\n"
    "\n"
    "print(f\"\\nStations with ALL WoSIS props missing (potential problem): \", end=\"\")\n"
    "empty = merged[prop_cols].isna().all(axis=1).sum()\n"
    "print(f\"{empty} ({empty/len(merged)*100:.1f}%)\")"
))

# ── Cell 7 — Phase 5: Visualisations ─────────────────────────────────────────
cells.append(nbf.v4.new_markdown_cell("## Phase 5 — Visualisations"))

cells.append(nbf.v4.new_code_cell(
    "fig = plt.figure(figsize=(20, 18))\n"
    "gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)\n"
    "\n"
    "# ---- Plot 1: Stations per country (top 20) --------------------------------\n"
    "ax1 = fig.add_subplot(gs[0, 0])\n"
    "top20 = inv_df.nlargest(20, \"n_stations\")[[\"country\",\"n_stations\"]].sort_values(\"n_stations\", ascending=True)\n"
    "ax1.barh(top20[\"country\"], top20[\"n_stations\"], color=\"steelblue\")\n"
    "ax1.set_xlabel(\"Number of stations\")\n"
    "ax1.set_title(\"Top 20 Countries by WoSIS Station Count\")\n"
    "ax1.tick_params(axis='y', labelsize=8)\n"
    "\n"
    "# ---- Plot 2: WoSIS property coverage heatmap (top 20 countries) ----------\n"
    "ax2 = fig.add_subplot(gs[0, 1])\n"
    "top20_names = inv_df.nlargest(20, \"n_stations\")[\"country\"].tolist()\n"
    "heat_data = []\n"
    "for ctry in top20_names:\n"
    "    sub = merged[merged[\"country\"] == ctry]\n"
    "    if len(sub) == 0:\n"
    "        row_vals = [0.0] * len(prop_cols)\n"
    "    else:\n"
    "        row_vals = [sub[p].notna().sum() / len(sub) * 100 if p in sub.columns else 0.0\n"
    "                    for p in prop_cols]\n"
    "    heat_data.append(row_vals)\n"
    "import numpy as _np\n"
    "heat_arr = _np.array(heat_data)\n"
    "im = ax2.imshow(heat_arr, aspect='auto', cmap='YlGn', vmin=0, vmax=100)\n"
    "ax2.set_xticks(range(len(prop_cols)))\n"
    "ax2.set_xticklabels(prop_cols, rotation=45, ha='right', fontsize=7)\n"
    "ax2.set_yticks(range(len(top20_names)))\n"
    "ax2.set_yticklabels(top20_names, fontsize=7)\n"
    "ax2.set_title(\"WoSIS Property Coverage % (top 20 countries)\")\n"
    "plt.colorbar(im, ax=ax2, label=\"% non-null\")\n"
    "\n"
    "# ---- Plot 3: SoilGrids property coverage % overall -----------------------\n"
    "ax3 = fig.add_subplot(gs[1, 0])\n"
    "if len(sg_cols) > 0 and len(sg_df) > 0:\n"
    "    sg_cov = [(col, sg_df[col].notna().sum() / len(sg_df) * 100) for col in sg_cols]\n"
    "    sg_cov_df = pd.DataFrame(sg_cov, columns=[\"prop\",\"pct\"]).sort_values(\"pct\", ascending=True)\n"
    "    ax3.barh(sg_cov_df[\"prop\"], sg_cov_df[\"pct\"], color=\"darkorange\")\n"
    "    ax3.set_xlabel(\"Coverage (%)\")\n"
    "    ax3.set_xlim(0, 100)\n"
    "    ax3.axvline(50, color='red', linestyle='--', linewidth=0.8, label='50%')\n"
    "    ax3.legend(fontsize=7)\n"
    "ax3.set_title(\"SoilGrids Property Coverage % (all stations)\")\n"
    "ax3.tick_params(axis='y', labelsize=8)\n"
    "\n"
    "# ---- Plot 4: Validation scatter -- WoSIS pH vs SoilGrids phh2o ----------\n"
    "ax4 = fig.add_subplot(gs[1, 1])\n"
    "ph_col = next((c for c in merged.columns if c.lower() in ['ph','phh2o','ph_water']), None)\n"
    "sg_ph_col = 'sg_phh2o' if 'sg_phh2o' in merged.columns else None\n"
    "if ph_col and sg_ph_col:\n"
    "    valid = merged[[ph_col, sg_ph_col]].dropna()\n"
    "    ax4.scatter(valid[ph_col], valid[sg_ph_col], alpha=0.3, s=10, color='purple')\n"
    "    mn = min(valid[ph_col].min(), valid[sg_ph_col].min())\n"
    "    mx = max(valid[ph_col].max(), valid[sg_ph_col].max())\n"
    "    ax4.plot([mn, mx], [mn, mx], 'r--', linewidth=1, label='1:1 line')\n"
    "    ax4.set_xlabel(f'WoSIS {ph_col}')\n"
    "    ax4.set_ylabel('SoilGrids phh2o')\n"
    "    ax4.set_title(f'Validation: WoSIS {ph_col} vs SoilGrids phh2o (n={len(valid):,})')\n"
    "    ax4.legend(fontsize=8)\n"
    "else:\n"
    "    ax4.text(0.5, 0.5, 'pH data not available for scatter\\n(check property names)',\n"
    "             ha='center', va='center', transform=ax4.transAxes, fontsize=10)\n"
    "    ax4.set_title('Validation: WoSIS pH vs SoilGrids phh2o')\n"
    "\n"
    "fig_path = os.path.join(OUTPUT_DIR, \"nb08_consolidation_overview.png\")\n"
    "plt.savefig(fig_path, dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f\"Figure saved: {fig_path}\")"
))

# ── Cell 8 — Save outputs + Summary ──────────────────────────────────────────
cells.append(nbf.v4.new_markdown_cell("## Save Outputs & Summary"))

cells.append(nbf.v4.new_code_cell(
    "# Save merged dataset\n"
    "out_path = \"/home/agbelgaid/Documents/WORKSPACE/DataCollection/SoilHive/data/combined_soilhive_dataset.parquet\"\n"
    "merged.to_parquet(out_path, index=False)\n"
    "print(f\"Merged dataset saved: {out_path}\")\n"
    "print(f\"File size: {os.path.getsize(out_path)/1e6:.2f} MB\")\n"
    "\n"
    "# Also save inventory\n"
    "inv_out = os.path.join(OUTPUT_DIR, \"nb08_inventory.csv\")\n"
    "inv_df[[col for col in inv_df.columns if col not in ['wosis_props','sg_props']]].to_csv(inv_out, index=False)\n"
    "print(f\"Inventory saved: {inv_out}\")\n"
    "\n"
    "print()\n"
    "print(\"=\" * 70)\n"
    "print(\"SYNTHESE NB08 - Consolidation SoilHive\")\n"
    "print(\"=\" * 70)\n"
    "print(f\"Countries processed    : {len(countries)}\")\n"
    "print(f\"Total WoSIS stations   : {wosis_wide.shape[0]:,}\")\n"
    "print(f\"Total WoSIS rows       : {len(wosis_df):,}\")\n"
    "print(f\"SoilGrids props        : {len(sg_cols)}\")\n"
    "print(f\"Merged dataset shape   : {merged.shape}\")\n"
    "print(f\"Stations empty (WoSIS) : {empty} ({empty/len(merged)*100:.1f}%)\")\n"
    "print(f\"Issues logged          : {len(issues) + len(sg_errors)}\")\n"
    "print(f\"Output saved to        : combined_soilhive_dataset.parquet\")"
))

nb.cells = cells

nbf.write(nb, NB_PATH)
print(f"Notebook written: {NB_PATH}")
print(f"Total cells: {len(nb.cells)}")
